const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STORAGE="vml-emily-",TARGET_IDS=["OB-0119","OB-0120","OB-0121","OB-0122","OB-0123"];
let creator=null,arrangements=[],selected=0;
function baseTitle(title){return VML.clean(title).replace(/\s*[—-]\s*adaptaci[oó]n coral\s*$/i,"")}
function getArrangements(c){const works=c?.works||[];const exact=works.filter(w=>TARGET_IDS.includes(w.id));return exact.length?exact:works.filter(w=>/adaptaci[oó]n coral/i.test(w.title||""))}
function renderData(){
  $("#context-bio").innerHTML=`<p>${VML.safe(creator.bio||"Biografía pendiente de validación editorial.")}</p><p><strong>Nacimiento:</strong> ${VML.safe(creator.birth||"Por verificar")} · <strong>Lugar:</strong> ${VML.safe(creator.place||"Por verificar")}</p><p class="source-note"><strong>Fuente:</strong> ${VML.safe(creator.source||"Pendiente")}</p>`;
  $("#context-works").innerHTML=arrangements.map(w=>`<div class="border-bottom py-2"><strong>${VML.safe(baseTitle(w.title))}</strong><br><small class="text-secondary">${VML.safe(w.type||"Adaptación coral")}</small></div>`).join("")||"<p>Corpus pendiente de carga.</p>";
  $("#arrangement-selector").innerHTML=arrangements.map((w,i)=>`<button class="work-choice${i===selected?" selected":""}" data-work="${i}" aria-pressed="${i===selected}"><strong>${i+1}.</strong> ${VML.safe(baseTitle(w.title))}</button>`).join("");
  $$('[data-work]').forEach(b=>b.addEventListener('click',()=>selectWork(Number(b.dataset.work))));selectWork(selected);
}
function selectWork(i){if(!arrangements.length)return;selected=Math.max(0,Math.min(i,arrangements.length-1));const w=arrangements[selected],title=baseTitle(w.title);localStorage.setItem(STORAGE+"work",String(selected));$$('[data-work]').forEach((b,n)=>{b.classList.toggle('selected',n===selected);b.setAttribute('aria-pressed',String(n===selected))});$("#original-title").textContent=title;$("#arranged-title").textContent=VML.clean(w.title);$("#arranged-meta").textContent=`${w.role||"Arreglo"} · ${w.type||"Adaptación coral"}`;$("#selected-work-station3").textContent=title;$("#selected-work-station4").textContent=title}
function showStation(n,move=true){$$('.station').forEach(x=>{const on=Number(x.dataset.panel)===n;x.classList.toggle('active',on);x.setAttribute('aria-hidden',String(!on))});$$('.station-btn').forEach(x=>{const on=Number(x.dataset.station)===n;x.classList.toggle('active',on);x.setAttribute('aria-selected',String(on))});const pct=n*20;$("#progress-label").textContent=`Estación ${n} de 5`;$("#progress-percent").textContent=pct+"%";$("#progress-bar").style.width=pct+"%";$(".lab-progress").setAttribute('aria-valuenow',String(pct));localStorage.setItem(STORAGE+"station",String(n));if(move)window.scrollTo({top:document.querySelector('.station-nav').offsetTop,behavior:'smooth'})}
function restore(){$$('[data-save]').forEach(el=>{const v=localStorage.getItem(STORAGE+el.dataset.save);if(v!==null)el.value=v});$$('[data-transform]').forEach(b=>{const on=localStorage.getItem(STORAGE+"transform-"+b.dataset.transform)==='1';b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))});const c=localStorage.getItem(STORAGE+"create");$$('[data-create-choice]').forEach(b=>{const on=b.dataset.createChoice===c;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))});showStation(Number(localStorage.getItem(STORAGE+"station")||1),false)}
$$('.station-btn').forEach(b=>b.addEventListener('click',()=>showStation(Number(b.dataset.station))));$$('.next-station').forEach(b=>b.addEventListener('click',()=>showStation(Number(b.dataset.next))));$$('[data-save]').forEach(el=>el.addEventListener('input',()=>localStorage.setItem(STORAGE+el.dataset.save,el.value)));$$('[data-transform]').forEach(b=>b.addEventListener('click',()=>{const on=!b.classList.contains('selected');b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));localStorage.setItem(STORAGE+"transform-"+b.dataset.transform,on?'1':'0')}));$$('[data-create-choice]').forEach(b=>b.addEventListener('click',()=>{$$('[data-create-choice]').forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false')});b.classList.add('selected');b.setAttribute('aria-pressed','true');localStorage.setItem(STORAGE+"create",b.dataset.createChoice)}));
$("#complete-lab").addEventListener('click',()=>{localStorage.setItem(STORAGE+"complete",'1');$("#completion-message").innerHTML='<div class="alert alert-light">Completado en este navegador. Revisa o copia tus respuestas para compartirlas.</div>'});
VML.load().then(data=>{creator=(data.creators||[]).find(c=>c.id==='CR-058');if(!creator)throw new Error('No se encontró CR-058');arrangements=getArrangements(creator);selected=Number(localStorage.getItem(STORAGE+"work")||0);$("#lab-status").textContent=VML.modeLabel()+" · "+arrangements.length+" adaptaciones documentadas";renderData();restore()}).catch(e=>{creator={bio:"Perfil documental de Emily Katherine Ordóñez Celi.",birth:"2002",place:"Pendiente de verificación",source:"Base Maestra del proyecto"};arrangements=["Loja en septiembre de flores","Cecilia","Primaveral","La voz del maizal","Sobre el pajonal"].map((title,i)=>({id:TARGET_IDS[i],title:title+" — adaptación coral",type:"Adaptación coral",role:"Arreglo"}));$("#lab-status").textContent="Vista de respaldo · no fue posible actualizar la Base Maestra: "+e.message;renderData();restore()});
