const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let creator=null;
function jsonp(baseUrl,mode="preview",timeout=12000){return new Promise((resolve,reject)=>{const cb="__em_"+Date.now()+"_"+Math.random().toString(36).slice(2);const s=document.createElement("script");const sep=baseUrl.includes("?")?"&":"?";s.src=`${baseUrl}${sep}mode=${encodeURIComponent(mode)}&callback=${encodeURIComponent(cb)}`;let done=false;const clean=()=>{if(done)return;done=true;if(s.parentNode)s.remove();try{delete window[cb]}catch(_){}clearTimeout(t)};window[cb]=d=>{clean();resolve(d)};s.onerror=()=>{clean();reject(new Error("No se pudo cargar la API"))};const t=setTimeout(()=>{clean();reject(new Error("Tiempo de espera agotado"))},timeout);document.head.appendChild(s)})}
function cleanTitle(s){return String(s||"").replace(/^["']|["']$/g,"").replace(/\.$/,"").trim()}
async function init(){try{const data=await jsonp(window.VML_CONFIG.API_URL,window.VML_CONFIG.API_MODE||"preview");creator=(data.creators||[]).find(c=>c.id==="CR-058");if(!creator)throw new Error("No se encontró CR-058");$("#lab-status").textContent="Modo vista previa · información cargada desde Google Sheets";renderData();restore()}catch(e){$("#lab-status").textContent="No fue posible cargar la información: "+e.message}}
function renderData(){
 $("#context-bio").innerHTML=`<p>${creator.bio||"Biografía pendiente de validación y redacción editorial."}</p><p><strong>Nacimiento:</strong> ${creator.birth||"Por verificar"} · <strong>Lugar:</strong> ${creator.place||"Por verificar"}</p><p><strong>Fuente:</strong> ${creator.source||"Pendiente"}</p>`;
 $("#context-works").innerHTML=(creator.works||[]).map(w=>`<div class="border-bottom py-2"><strong>${cleanTitle(w.title)}</strong><br><small class="text-secondary">${w.type||"Por clasificar"} · ${w.role||"Rol por verificar"}</small></div>`).join("");
}
function showStation(n){$$(".station").forEach(x=>x.classList.toggle("active",x.dataset.panel==n));$$(".station-btn").forEach(x=>x.classList.toggle("active",x.dataset.station==n));const pct=n*20;$("#progress-label").textContent=`Estación ${n} de 5`;$("#progress-percent").textContent=pct+"%";$("#progress-bar").style.width=pct+"%";localStorage.setItem("vml-em-station",n)}
$$(".station-btn").forEach(b=>b.addEventListener("click",()=>showStation(Number(b.dataset.station))));$$(".next-station").forEach(b=>b.addEventListener("click",()=>showStation(Number(b.dataset.next))));$$("[data-save]").forEach(el=>el.addEventListener("input",()=>localStorage.setItem("vml-em-"+el.dataset.save,el.value)));$$("[data-transform]").forEach(b=>b.addEventListener("click",()=>{b.classList.toggle("selected");localStorage.setItem("vml-em-transform-"+b.dataset.transform,b.classList.contains("selected")?"1":"0")}));$$("[data-create-choice]").forEach(b=>b.addEventListener("click",()=>{$$("[data-create-choice]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");localStorage.setItem("vml-em-create",b.dataset.createChoice)}));$("#complete-lab").addEventListener("click",()=>{localStorage.setItem("vml-em-complete","1");$("#completion-message").innerHTML='<div class="alert alert-light">Laboratorio marcado como completado en este navegador.</div>'});
function restore(){$$("[data-save]").forEach(el=>{const v=localStorage.getItem("vml-em-"+el.dataset.save);if(v!==null)el.value=v});$$("[data-transform]").forEach(b=>{if(localStorage.getItem("vml-em-transform-"+b.dataset.transform)==="1")b.classList.add("selected")});const c=localStorage.getItem("vml-em-create");if(c){const b=document.querySelector(`[data-create-choice="${c}"]`);if(b)b.classList.add("selected")}showStation(Number(localStorage.getItem("vml-em-station")||1))}
init();